### PR TITLE
Upgrade package.json...

### PR DESCRIPTION
**Pull request by caionitro**
upgrading the package.json, we need to upgrade server.js too. 
- Package.json
-   Express 3 -> Express 4
-   Mongooose 3.6 to Mongoose 3.8.
- server.js
-   app.configure deprecated in express4.
-   methodOverride and bodyParser required on top.

### CODE REVIEW

**Comment by chris-sev** [comment]
Great stuff. Could you add comments to lines 16-20 of server.js to explain the use for all those? We want to keep things well commented to explain to new users what's going on.

**Comment by caionitro** [comment]
Of course! why not? ;]

Done!

**Comment by chris-sev** [comment]
Great thanks!

**Comment by chris-sev** [comment]
Updated the corresponding article and added a link back to your GitHub account at the bottom of the article @caionitro.

Thanks again.

**Pull request merged**
